### ISSUE TITLE
Heating profile storage without Google services

### ISSUE THREAD

**Issue by dktzde** [jutzig/max-remote#5]
I have been using the app for many years with great pleasure - thank you very much!

I've just changed my mobile phone and have decided not to install Google services for personal data protection reasons.

When I forget to remove "Sync with Google Drive" in the settings, I get the following error message when I try to save a heating profile: "The profile could not be saved:NetworkError"

Backup: I can easily save and restore the heating profiles using Android's on-board backup solution ([SeedVault ](https://github.com/seedvault-app/seedvault) in my case). Restore also worked without any problems when setting up the mobile phone.

Info: I use a Google Pixel 3 with [DivestOS](https://www.kuketz-blog.de/divestos-datenschutzfreundlich-und-erhoehte-sicherheit-custom-roms-teil5/). I have installed and use microG (non-privileged). I have not set up a Google account.

**Comment by jutzig** [comment]
Yeah, when drive sync is active, it tries to store it directly to drive when saving a profile, and it's clear that it won't work without Google services.
But it works when you deactivate the drive sync, correct? If so, I'm not sure what the issue is, that sounds like the expected behavior

**Comment by dktzde** [comment]
No, there is no problem. The post was more for information in case someone is in a similar situation.
